In [20]:
import pandas as pd
import numpy as np 
import sklearn
import lightgbm
import statsmodels
import matplotlib


train_df = pd.read_json('../data/train.json')
train_df.head()

# Снимаем ограничения на максимальное количество выводимых колонок и строк
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Округлим вывод чисел в таблице до 3 знаков после запятой для читаемости
pd.set_option('display.float_format', '{:.3f}'.format)

In [21]:
train_df.shape

(49352, 15)

In [22]:
print(train_df.corr(numeric_only=True))

            bathrooms  bedrooms  latitude  listing_id  longitude  price
bathrooms       1.000     0.533    -0.010       0.001      0.010  0.070
bedrooms        0.533     1.000    -0.005       0.012      0.007  0.052
latitude       -0.010    -0.005     1.000       0.002     -0.967 -0.001
listing_id      0.001     0.012     0.002       1.000     -0.001  0.008
longitude       0.010     0.007    -0.967      -0.001      1.000 -0.000
price           0.070     0.052    -0.001       0.008     -0.000  1.000

In [23]:
train_df.info()

<class 'pandas.DataFrame'>
Index: 49352 entries, 4 to 124009
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   bathrooms        49352 non-null  float64
 1   bedrooms         49352 non-null  int64
 2   building_id      49352 non-null  str
 3   created          49352 non-null  str
 4   description      49352 non-null  str
 5   display_address  49352 non-null  str
 6   features         49352 non-null  object
 7   latitude         49352 non-null  float64
 8   listing_id       49352 non-null  int64
 9   longitude        49352 non-null  float64
 10  manager_id       49352 non-null  str
 11  photos           49352 non-null  object
 12  price            49352 non-null  int64
 13  street_address   49352 non-null  str
 14  interest_level   49352 non-null  str
dtypes: float64(3), int64(3), object(2), str(7)
memory usage: 6.0+ MB

In [24]:
train_df['created']

4         2016-06-16 05:55:27
6         2016-06-01 05:44:33
9         2016-06-14 15:19:59
10        2016-06-24 07:54:24
15        2016-06-28 03:50:23
16        2016-06-28 05:59:06
18        2016-06-08 06:21:36
19        2016-06-05 05:28:22
23        2016-06-09 04:42:03
32        2016-06-28 03:26:18
33        2016-06-04 02:21:27
36        2016-06-01 02:51:22
38        2016-06-25 05:28:30
39        2016-06-11 03:46:53
42        2016-06-11 04:24:39
43        2016-06-20 10:14:52
44        2016-06-11 03:59:20
46        2016-06-16 07:43:48
49        2016-06-16 03:23:57
61        2016-06-25 01:35:36
66        2016-06-24 02:16:54
67        2016-06-10 02:44:56
69        2016-06-14 02:28:02
74        2016-06-02 02:37:02
78        2016-06-09 05:38:52
80        2016-06-20 19:09:31
82        2016-06-05 11:31:08
83        2016-06-29 04:52:59
84        2016-06-29 02:40:31
85        2016-06-01 03:38:31
87        2016-06-25 06:08:16
88        2016-06-16 03:11:45
89        2016-06-08 06:18:46
92        2016-06-14 15:40:55
93        2016-06-04 06:43:37
101       2016-06-12 13:35:11
102       2016-06-23 03:49:49
104       2016-06-29 03:39:34
106       2016-06-24 07:55:11
107       2016-06-21 07:52:50
111       2016-06-19 21:39:44
113       2016-06-24 02:43:21
115       2016-06-08 06:14:34
117       2016-06-17 01:22:28
118       2016-06-24 06:19:48
121       2016-06-07 03:59:42
122       2016-06-10 02:10:41
133       2016-06-16 19:52:09
136       2016-06-14 10:33:41
139       2016-06-16 08:13:13
140       2016-06-25 05:28:33
145       2016-06-26 14:25:31
146       2016-06-11 02:11:29
151       2016-06-24 02:29:12
152       2016-06-01 05:01:58
158       2016-06-02 03:30:19
161       2016-06-03 20:27:46
170       2016-06-16 02:32:28
171       2016-06-16 03:32:12
181       2016-06-02 04:35:31
182       2016-06-29 04:58:28
186       2016-06-10 05:11:29
192       2016-06-15 04:49:55
194       2016-06-23 04:05:04
200       2016-06-25 04:02:05
204       2016-06-27 02:56:03
205       2016-06-26 03:01:18
206       2016-06-12 09:59:54
208       2016-06-10 02:14:42
214       2016-06-21 07:29:05
217       2016-06-22 03:23:28
226       2016-06-01 04:54:19
228       2016-06-09 02:45:18
235       2016-06-04 02:33:12
236       2016-06-29 05:44:55
237       2016-06-14 12:59:16
241       2016-06-07 01:42:14
244       2016-06-21 07:32:09
245       2016-06-20 18:46:53
246       2016-06-04 06:07:27
247       2016-06-12 11:29:24
248       2016-06-11 04:56:15
249       2016-06-10 02:23:18
251       2016-06-29 06:28:34
252       2016-06-16 02:17:21
255       2016-06-10 02:53:21
257       2016-06-12 09:47:17
262       2016-06-05 20:44:11
263       2016-06-24 06:52:53
272       2016-06-22 05:25:03
275       2016-06-17 04:08:49
277       2016-06-05 02:28:37
279       2016-06-16 05:29:33
280       2016-06-09 02:53:39
282       2016-06-21 05:56:44
283       2016-06-10 05:34:41
284       2016-06-09 02:40:47
289       2016-06-16 02:38:27
291       2016-06-21 01:44:38
292       2016-06-26 03:52:06
293       2016-06-21 07:24:50
295       2016-06-28 02:14:42
296       2016-06-22 02:23:07
303       2016-06-03 03:57:51
304       2016-06-05 02:12:45
305       2016-06-16 07:42:51
309       2016-06-15 02:20:40
311       2016-06-10 03:34:34
312       2016-06-09 02:26:42
313       2016-06-08 04:18:12
314       2016-06-12 12:48:11
315       2016-06-28 02:32:15
320       2016-06-28 02:12:29
322       2016-06-16 18:00:48
323       2016-06-23 01:10:43
325       2016-06-15 02:14:16
332       2016-06-28 05:21:40
333       2016-06-02 02:17:38
335       2016-06-29 17:47:34
336       2016-06-29 03:37:26
337       2016-06-08 06:37:00
338       2016-06-16 03:09:49
340       2016-06-21 04:42:52
341       2016-06-07 05:02:51
343       2016-06-27 01:27:20
344       2016-06-03 03:48:08
348       2016-06-15 05:02:06
351       2016-06-08 03:49:42
355       2016-06-27 02:34:52
356       2016-06-25 03:22:53
359       2016-06-06 17:10:08
360       2016-06-10 05:37:22
361       2016-06-10 14:52:38
362       2016-06-12 11:42:22
365       2016-06-11 18:30:32
370       2016-06-02 17:20:40
373       2016-06-27 02:43:46
374       2016-06-26 03:56:19
375       2016-06-02 02:11:38
377       2016-06-23 02:17:59
379       2016-06-01 01:40:25
380       2016-06-29 02:56:21
381       2016-06-24 02:27:14
383       2016-06-07 05:36:13
386       2016-06-04 02:33:37
387       2016-06-10 05:01:21
390       2016-06-12 05:24:44
392       2016-06-16 08:27:09
393       2016-06-28 02:17:51
394       2016-06-08 05:35:43
396       2016-06-13 01:17:22
397       2016-06-02 02:37:49
398       2016-06-16 05:06:59
408       2016-06-16 01:37:02
409       2016-06-25 02:55:37
412       2016-06-09 06:05:53
415       2016-06-03 05:52:12
417       2016-06-03 06:10:21
419       2016-06-05 02:56:03
424       2016-06-21 05:35:57
425       2016-06-03 05:58:19
437       2016-06-07 05:46:58
438       2016-06-10 05:06:44
440       2016-06-04 04:23:42
441       2016-06-06 02:36:13
442       2016-06-12 04:57:16
444       2016-06-25 04:57:28
445       2016-06-15 16:57:57
446       2016-06-26 20:33:54
447       2016-06-10 04:48:14
449       2016-06-29 05:51:35
451       2016-06-03 05:52:18
454       2016-06-08 05:46:10
458       2016-06-05 01:32:36
465       2016-06-12 05:14:31
466       2016-06-01 05:40:53
471       2016-06-14 02:20:00
472       2016-06-29 03:58:17
473       2016-06-02 02:33:53
474       2016-06-23 03:06:10
476       2016-06-21 01:44:26
479       2016-06-14 11:50:34
480       2016-06-23 04:29:05
481       2016-06-06 15:54:29
482       2016-06-27 01:39:40
483       2016-06-25 01:40:02
484       2016-06-28 06:04:51
486       2016-06-11 02:36:31
487       2016-06-14 15:24:57
490       2016-06-29 06:28:45
491       2016-06-11 02:54:46
494       2016-06-11 04:32:31
498       2016-06-12 02:46:30
499       2016-06-24 03:29:03
500       2016-06-08 05:01:30
506       2016-06-12 09:52:20
509       2016-06-21 04:29:11
510       2016-06-20 18:21:45
511       2016-06-03 06:03:35
513       2016-06-22 04:50:06
514       2016-06-29 05:48:21
515       2016-06-02 04:12:42
518       2016-06-21 01:45:27
519       2016-06-23 02:24:21
521       2016-06-13 02:52:46
529       2016-06-25 01:29:46
530       2016-06-29 02:33:10
534       2016-06-21 13:27:51
535       2016-06-09 02:17:05
536       2016-06-22 06:25:56
537       2016-06-14 15:55:56
538       2016-06-12 02:52:38
542       2016-06-09 05:54:29
548       2016-06-09 01:21:30
554       2016-06-15 05:56:54
555       2016-06-27 05:22:01
557       2016-06-21 05:48:58
558       2016-06-11 04:07:42
561       2016-06-20 12:11:17
563       2016-06-01 02:10:45
564       2016-06-15 02:32:03
567       2016-06-11 01:20:36
568       2016-06-21 02:55:37
569       2016-06-15 05:45:14
571       2016-06-15 02:40:34
572       2016-06-09 05:21:45
573       2016-06-23 03:18:35
576       2016-06-21 03:11:20
577       2016-06-07 04:11:40
582       2016-06-02 06:51:35
585       2016-06-15 06:23:56
587       2016-06-01 05:29:44
589       2016-06-14 15:31:33
590       2016-06-12 01:32:27
592       2016-06-16 06:06:15
597       2016-06-12 02:25:26
598       2016-06-17 02:16:33
599       2016-06-21 01:58:03
600       2016-06-03 01:47:11
604       2016-06-16 22:10:31
605       2016-06-24 02:24:28
607       2016-06-16 03:24:48
610       2016-06-06 02:50:15
614       2016-06-12 12:01:41
615       2016-06-22 05:49:20
620       2016-06-07 02:44:27
621       2016-06-05 04:00:17
622       2016-06-29 18:14:48
623       2016-06-27 01:24:51
624       2016-06-16 02:01:40
626       2016-06-16 04:15:23
629       2016-06-01 05:23:40
631       2016-06-05 03:28:05
636       2016-06-06 18:10:37
638       2016-06-14 12:43:32
640       2016-06-11 06:38:46
641       2016-06-20 19:00:28
644       2016-06-24 05:45:01
645       2016-06-09 04:58:30
647       2016-06-01 04:25:01
648       2016-06-07 04:04:02
649       2016-06-25 02:48:22
651       2016-06-21 04:50:08
656       2016-06-20 18:54:35
657       2016-06-04 01:21:00
658       2016-06-01 05:30:40
659       2016-06-29 03:09:18
662       2016-06-21 05:22:03
666       2016-06-04 05:54:32
669       2016-06-02 06:23:29
674       2016-06-28 05:03:18
675       2016-06-16 03:32:52
679       2016-06-29 06:38:19
681       2016-06-21 07:26:46
682       2016-05-31 22:46:46
685       2016-06-17 03:16:14
687       2016-06-24 04:22:26
692       2016-06-28 02:23:02
693       2016-06-11 05:25:45
694       2016-06-03 03:06:14
696       2016-06-12 13:06:44
699       2016-06-13 03:23:24
700       2016-06-21 05:58:59
703       2016-06-14 15:22:01
704       2016-06-16 06:13:59
705       2016-06-29 01:27:53
706       2016-06-12 06:50:18
707       2016-06-02 07:04:22
712       2016-06-24 07:19:48
714       2016-06-13 01:18:41
715       2016-06-23 03:05:50
716       2016-06-07 06:15:07
718       2016-06-16 03:42:32
720       2016-06-06 01:22:40
725       2016-06-28 02:41:02
728       2016-06-10 02:40:57
730       2016-06-28 05:52:35
735       2016-06-05 02:36:32
737       2016-06-01 01:11:52
740       2016-06-15 01:39:18
741       2016-06-18 01:38:12
742       2016-06-28 02:52:25
743       2016-06-24 03:51:12
747       2016-06-04 01:23:27
749       2016-06-14 15:23:47
754       2016-06-16 08:26:16
757       2016-06-22 05:44:56
761       2016-06-21 01:35:01
762       2016-06-08 04:32:35
764       2016-06-09 03:41:07
766       2016-06-11 02:57:33
770       2016-06-24 05:02:21
772       2016-06-03 03:50:08
773       2016-06-01 04:47:17
776       2016-06-07 02:12:02
778       2016-06-10 16:12:11
783       2016-06-03 01:28:34
786       2016-06-12 01:20:31
788       2016-06-10 03:15:33
791       2016-06-23 01:25:15
798       2016-06-14 02:22:19
801       2016-06-10 05:34:55
806       2016-06-23 21:08:20
807       2016-06-04 06:00:04
809       2016-06-25 02:51:36
810       2016-06-09 03:44:58
812       2016-06-12 13:36:06
813       2016-06-01 02:27:47
815       2016-06-16 03:30:13
816       2016-06-14 15:37:15
818       2016-06-15 06:21:37
820       2016-06-08 03:21:36
821       2016-06-29 04:24:13
822       2016-06-20 18:43:28
828       2016-06-21 06:22:25
833       2016-06-16 01:42:21
836       2016-06-28 03:24:09
839       2016-06-07 03:33:47
840       2016-06-14 12:02:21
841       2016-06-26 02:25:05
843       2016-06-01 05:22:20
845       2016-06-10 04:18:32
846       2016-06-22 13:36:24
847       2016-06-16 05:37:02
849       2016-06-09 02:28:56
850       2016-06-14 15:57:09
852       2016-06-16 02:56:50
858       2016-06-25 03:39:54
859       2016-06-09 04:10:57
862       2016-06-14 12:46:25
863       2016-06-13 01:24:01
865       2016-06-17 02:28:34
866       2016-06-28 01:39:08
872       2016-06-11 06:44:25
873       2016-06-09 01:18:00
875       2016-06-02 02:33:54
876       2016-06-11 05:53:33
877       2016-06-07 02:10:09
878       2016-06-20 19:03:47
879       2016-06-29 06:13:19
880       2016-06-02 02:19:38
881       2016-06-22 03:38:29
883       2016-06-08 02:26:04
884       2016-06-14 12:53:50
886       2016-06-08 06:11:54
889       2016-06-16 07:41:14
892       2016-06-12 08:16:40
893       2016-06-01 04:19:14
897       2016-06-01 05:42:24
898       2016-06-01 02:14:08
899       2016-06-21 01:44:45
901       2016-06-01 02:29:05
903       2016-06-16 02:11:51
910       2016-06-01 02:41:47
914       2016-06-23 03:33:45
917       2016-06-03 03:24:33
918       2016-06-21 07:01:25
921       2016-06-16 05:28:34
923       2016-06-16 05:54:58
925       2016-06-15 14:38:36
928       2016-06-24 02:01:03
936       2016-06-24 04:41:08
937       2016-06-11 03:57:58
938       2016-06-21 07:17:43
939       2016-06-03 06:09:25
941       2016-06-17 06:10:12
944       2016-06-07 02:55:43
945       2016-06-10 03:49:48
947       2016-06-01 05:47:23
948       2016-06-21 03:12:33
953       2016-06-09 01:12:24
956       2016-06-02 06:42:33
958       2016-06-08 02:26:18
959       2016-06-28 14:22:07
962       2016-06-11 04:47:05
963       2016-06-20 19:01:32
964       2016-06-12 12:12:51
965       2016-06-06 02:33:28
967       2016-06-20 18:07:45
969       2016-06-25 01:22:16
973       2016-06-25 03:11:40
975       2016-06-15 02:28:14
976       2016-06-20 18:46:06
978       2016-06-08 05:28:32
979       2016-06-26 02:39:31
980       2016-06-09 03:17:31
981       2016-06-14 15:23:04
984       2016-06-20 18:57:10
985       2016-06-10 01:18:27
987       2016-06-10 02:19:07
988       2016-06-06 02:27:51
993       2016-06-28 02:23:59
997       2016-06-10 03:31:06
998       2016-06-11 03:15:03
1002      2016-06-24 05:04:03
1004      2016-06-21 07:53:41
1007      2016-06-09 06:28:02
1010      2016-06-09 01:47:42
1015      2016-06-08 03:03:51
1016      2016-06-02 02:32:24
1017      2016-06-12 13:52:49
1019      2016-06-12 03:42:14
1020      2016-06-15 02:43:35
1021      2016-06-11 01:39:54
1022      2016-06-12 02:26:58
1023      2016-06-04 05:05:59
1024      2016-06-07 06:04:12
1025      2016-06-07 04:23:15
1026      2016-06-18 02:30:58
1027      2016-06-22 02:30:37
1030      2016-06-12 04:23:14
1031      2016-06-15 10:19:43
1036      2016-06-08 05:44:32
1037      2016-06-12 13:26:18
1038      2016-06-05 03:28:00
1039      2016-06-29 01:38:34
1041      2016-06-22 05:25:13
1044      2016-06-04 06:10:48
1045      2016-06-14 15:48:15
1047      2016-06-14 02:21:11
1048      2016-06-03 02:12:06
1053      2016-06-28 05:20:03
1056      2016-06-24 04:37:14
1058      2016-06-01 06:11:06
1060      2016-06-16 01:15:11
1063      2016-06-16 06:23:29
1064      2016-06-09 18:03:43
1065      2016-06-07 02:30:29
1066      2016-06-01 05:24:45
1067      2016-06-11 03:45:36
1071      2016-06-14 12:50:30
1075      2016-06-02 07:11:32
1076      2016-06-12 12:06:13
1078      2016-06-02 04:53:54
1083      2016-06-22 02:11:01
1084      2016-06-15 03:11:15
1087      2016-06-24 08:30:30
1088      2016-06-02 04:13:01
1089      2016-06-03 01:46:14
1090      2016-06-10 01:13:00
1091      2016-06-04 03:54:31
1092      2016-06-07 01:39:25
1093      2016-06-01 06:11:30
1094      2016-06-29 01:12:38
1096      2016-06-21 02:40:27
1097      2016-06-08 02:14:21
1099      2016-06-22 05:41:48
1105      2016-06-05 02:54:29
1107      2016-06-21 19:16:39
1111      2016-06-08 02:11:55
1114      2016-06-11 06:03:45
1115      2016-06-02 03:26:48
1117      2016-06-24 11:07:11
1118      2016-06-28 03:35:08
1119      2016-06-15 05:26:32
1120      2016-06-21 03:44:31
1133      2016-06-21 05:25:32
1135      2016-06-02 03:07:12
1137      2016-06-09 01:41:54
1142      2016-06-12 02:33:56
1144      2016-06-07 06:20:26
1148      2016-06-17 02:26:42
1152      2016-06-25 03:10:53
1159      2016-06-02 03:43:44
1162      2016-06-09 02:54:43
1165      2016-06-25 01:38:45
1167      2016-06-25 03:38:31
1169      2016-06-06 05:24:31
1170      2016-06-10 02:59:06
1171      2016-06-09 06:15:09
1176      2016-06-17 06:10:02
1177      2016-06-04 05:53:26
1179      2016-06-07 01:13:52
1180      2016-06-03 05:56:21
1181      2016-06-02 07:09:32
1182      2016-06-29 03:32:50
1183      2016-06-29 05:07:58
1184      2016-06-12 03:27:22
1185      2016-06-04 05:57:59
1187      2016-06-05 02:16:05
1189      2016-06-03 05:40:25
1190      2016-06-16 08:02:30
1196      2016-06-22 05:27:53
1198      2016-06-16 07:11:59
1200      2016-06-13 02:45:06
1201      2016-06-01 02:34:34
1202      2016-06-14 11:52:31
1204      2016-06-10 05:59:19
1206      2016-06-21 07:51:42
1211      2016-06-25 10:58:16
1212      2016-06-24 05:44:34
1216      2016-06-15 03:56:19
1220      2016-06-22 02:27:26
1221      2016-06-29 04:29:25
1225      2016-06-14 15:37:10
1226      2016-06-08 02:32:30
1228      2016-06-21 05:05:12
1230      2016-06-12 13:46:46
1231      2016-06-25 05:28:15
1232      2016-06-01 03:22:33
1234      2016-06-12 04:35:57
1236      2016-06-28 05:41:06
1241      2016-06-13 02:45:31
1242      2016-06-13 05:26:06
1245      2016-06-01 02:25:21
1250      2016-06-21 06:32:59
1255      2016-06-27 03:08:48
1263      2016-06-11 05:21:07
1267      2016-06-10 03:35:04
1276      2016-06-12 14:05:40
1279      2016-06-14 15:22:34
1280      2016-06-04 01:24:47
1283      2016-06-05 02:21:37
1286      2016-06-13 02:24:39
1290      2016-06-01 05:00:40
1293      2016-06-10 03:59:16
1294      2016-06-06 03:24:10
1298      2016-06-29 17:32:02
1300      2016-06-21 06:27:51
1304      2016-06-25 06:03:04
1305      2016-06-02 02:27:35
1307      2016-06-01 06:04:09
1308      2016-06-12 01:33:03
1316      2016-06-16 02:54:18
1318      2016-06-29 05:06:58
1321      2016-06-24 02:25:58
1323      2016-06-23 01:36:13
1325      2016-06-28 04:14:45
1327      2016-06-08 02:29:04
1328      2016-06-24 08:21:08
1330      2016-06-27 14:36:36
1332      2016-06-14 15:22:52
1336      2016-06-16 02:23:35
1338      2016-06-12 05:45:45
1339      2016-06-12 12:51:16
1340      2016-06-28 01:39:12
1341      2016-06-11 04:39:17
1343      2016-06-12 12:38:38
1346      2016-06-01 05:56:43
1347      2016-06-18 02:56:20
1348      2016-06-02 04:52:12
1353      2016-06-23 04:04:12
1354      2016-06-26 04:03:18
1356      2016-06-06 01:10:47
1357      2016-06-16 03:12:16
1358      2016-06-22 06:39:46
1360      2016-06-21 11:28:55
1366      2016-06-06 03:17:54
1374      2016-06-10 02:35:19
1378      2016-06-08 05:35:34
1379      2016-06-14 15:47:36
1383      2016-06-22 15:55:27
1385      2016-06-11 01:12:53
1388      2016-06-09 05:22:22
1390      2016-06-01 05:44:55
1392      2016-06-16 07:12:41
1393      2016-06-27 03:19:13
1399      2016-06-14 02:00:32
1401      2016-06-21 05:51:45
1402      2016-06-10 03:29:15
1405      2016-06-16 07:32:43
1407      2016-06-28 01:18:37
1408      2016-06-16 07:00:26
1411      2016-06-16 06:56:29
1412      2016-06-17 05:35:06
1414      2016-06-16 03:34:16
1417      2016-06-01 05:52:34
1418      2016-06-02 06:40:10
1420      2016-06-10 05:54:29
1427      2016-06-22 02:24:27
1430      2016-06-24 08:09:49
1432      2016-06-24 02:31:33
1433      2016-06-16 03:53:55
1435      2016-06-20 19:13:40
1436      2016-06-29 06:25:09
1445      2016-06-21 06:42:36
1446      2016-06-01 05:43:38
1450      2016-06-13 02:50:44
1453      2016-06-17 05:51:42
1457      2016-06-26 01:11:57
1461      2016-06-02 07:05:51
1471      2016-06-12 13:09:59
1475      2016-06-26 02:54:45
1478      2016-06-02 02:48:01
1481      2016-06-01 05:23:08
1482      2016-06-02 03:02:52
1485      2016-06-23 04:05:46
1486      2016-06-16 07:45:32
1487      2016-06-28 05:32:48
1493      2016-06-07 05:29:28
1496      2016-06-12 09:17:11
1498      2016-06-11 02:46:23
1499      2016-06-05 05:29:25
1503      2016-06-29 06:27:46
1512      2016-06-21 02:33:00
1514      2016-06-24 03:33:46
1521      2016-06-14 01:16:31
1522      2016-06-12 11:13:42
1523      2016-06-16 03:11:58
1527      2016-06-16 08:19:09
1528      2016-06-03 05:25:53
1531      2016-06-03 12:10:53
1532      2016-06-17 03:03:41
1536      2016-06-23 01:10:56
1538      2016-06-29 06:31:54
1541      2016-06-08 11:09:50
1546      2016-06-24 04:45:08
1550      2016-06-28 02:40:36
1554      2016-06-03 05:21:29
1563      2016-06-04 05:28:24
1567      2016-06-12 09:45:58
1569      2016-06-03 05:39:23
1571      2016-06-12 08:15:44
1574      2016-06-29 04:03:08
1576      2016-06-03 03:52:04
1578      2016-06-04 01:29:59
1580      2016-06-16 08:09:59
1582      2016-06-25 14:32:12
1583      2016-06-21 04:26:15
1585      2016-06-27 02:58:52
1586      2016-06-07 02:25:22
1588      2016-06-01 05:34:19
1590      2016-06-02 06:41:46
1591      2016-06-28 03:42:49
1593      2016-06-21 03:07:44
1595      2016-06-26 04:11:27
1596      2016-06-13 01:11:19
1597      2016-06-21 05:41:00
1603      2016-06-01 02:29:49
1605      2016-06-22 02:43:38
1607      2016-06-07 04:43:05
1608      2016-06-11 15:27:01
1611      2016-06-05 03:31:35
1612      2016-06-25 01:12:33
1620      2016-06-29 06:37:13
1621      2016-06-27 02:51:53
1624      2016-06-21 06:55:39
1629      2016-06-01 05:46:15
1634      2016-06-09 01:29:52
1635      2016-06-25 14:10:41
1636      2016-06-01 02:40:54
1637      2016-06-12 08:11:10
1640      2016-06-27 02:44:35
1644      2016-06-23 02:11:46
1649      2016-06-17 18:02:54
1650      2016-06-24 07:57:45

# Разделяем created на месяц, день, день недели и час

In [25]:
train_df['created'] = pd.to_datetime(train_df['created'])

train_df['month'] = train_df['created'].dt.month
train_df['day'] = train_df['created'].dt.day
train_df['day_of_week'] = train_df['created'].dt.dayofweek
train_df['hour'] = train_df['created'].dt.hour

print(train_df[['created','month','day','day_of_week','hour']].head())

               created  month  day  day_of_week  hour
4  2016-06-16 05:55:27      6   16            3     5
6  2016-06-01 05:44:33      6    1            2     5
9  2016-06-14 15:19:59      6   14            1    15
10 2016-06-24 07:54:24      6   24            4     7
15 2016-06-28 03:50:23      6   28            1     3

In [26]:
print(train_df['interest_level'].value_counts())

interest_level
low       34284
medium    11229
high       3839
Name: count, dtype: int64

# Переводим в проценты

In [27]:
print((train_df['interest_level'].value_counts(normalize=True) * 100).round(1))

interest_level
low      69.500
medium   22.800
high      7.800
Name: proportion, dtype: float64

# Заменяем слова на цифры с map  
### компьютер не воспринимает слова, соответсвенно для дальнейших операций с interest_level нужно перевести его в цифры

In [28]:
mapping = {'low': 0, 'medium': 1, 'high': 2}

train_df['interest_level_num'] = train_df['interest_level'].map(mapping)

print(train_df[['interest_level', 'interest_level_num']].head())

   interest_level  interest_level_num
4          medium                   1
6             low                   0
9          medium                   1
10         medium                   1
15            low                   0

In [29]:
train_df.info()

<class 'pandas.DataFrame'>
Index: 49352 entries, 4 to 124009
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bathrooms           49352 non-null  float64
 1   bedrooms            49352 non-null  int64
 2   building_id         49352 non-null  str
 3   created             49352 non-null  datetime64[us]
 4   description         49352 non-null  str
 5   display_address     49352 non-null  str
 6   features            49352 non-null  object
 7   latitude            49352 non-null  float64
 8   listing_id          49352 non-null  int64
 9   longitude           49352 non-null  float64
 10  manager_id          49352 non-null  str
 11  photos              49352 non-null  object
 12  price               49352 non-null  int64
 13  street_address      49352 non-null  str
 14  interest_level      49352 non-null  str
 15  month               49352 non-null  int32
 16  day                 49352 non-null  int32
 17  day_of_week         49352 non-null  int32
 18  hour                49352 non-null  int32
 19  interest_level_num  49352 non-null  int64
dtypes: datetime64[us](1), float64(3), int32(4), int64(4), object(2), str(6)
memory usage: 7.2+ MB

In [30]:
df = train_df[['bathrooms', 'bedrooms', 'interest_level_num', 'price']]

df.head()

    bathrooms  bedrooms  interest_level_num  price
4       1.000         1                   1   2400
6       1.000         2                   0   3800
9       1.000         2                   1   3495
10      1.500         3                   1   3000
15      1.000         0                   0   2795

In [31]:
print(train_df['price'].describe())

count     49352.000
mean       3830.174
std       22066.866
min          43.000
25%        2500.000
50%        3150.000
75%        4100.000
max     4490000.000
Name: price, dtype: float64

# Добавляем признаки

In [33]:
# Создаем квадрат для количества ванных комнат
train_df['bathrooms_squared'] = train_df['bathrooms'] ** 2

# 2. Создаем квадрат для количества спален
train_df['bedrooms_squared'] = train_df['bedrooms'] ** 2

# 3. Создаём квадрат для цены
train_df['price_square'] = train_df['price'] ** 2

# 4. Создаём квадрат для объединёных ванных с спальнями. 
train_df['total_rooms'] = train_df['bathrooms'] + train_df['bedrooms']

# 5. Добавляем соотношение ванных к спальням
# Добавляем 0.1, чтобы случайно не разделилось на ноль, если спален 0
train_df['bath_to_bed_ratio'] = train_df['bathrooms'] / (train_df['bedrooms'] + 0.1)

# 6. Длина описания объявления
train_df['desc_length'] = train_df['description'].str.len().fillna(0)


# Проверяем, что новые столбцы успешно добавились
display(train_df[['bathrooms', 'bathrooms_squared', 'bedrooms', 'bedrooms_squared', 'total_rooms', 'price_square', 'bath_to_bed_ratio', 'desc_length']].head())

,bathrooms,bathrooms_squared,bedrooms,bedrooms_squared,total_rooms,price_square,bath_to_bed_ratio,desc_length
4,1.000,1.000,1,1,2.000,5760000,0.909,553
6,1.000,1.000,2,4,3.000,14440000,0.476,827
9,1.000,1.000,2,4,3.000,12215025,0.476,799
10,1.500,2.250,3,9,4.500,9000000,0.484,588
15,1.000,1.000,0,0,1.000,7812025,10.000,344